package Threads.Threads;

public class ResultTask extends Thread {

    public void run(){
        System.out.println("Result generated by: " + Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run(); // Normal Execution -> always the main thread
        t1.start(); // Multi Threading
        // start internally calls run()
        //✅Thread cannot be started twice
    }
}
